/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Owner
 */
public class GUI extends javax.swing.JFrame {

  private final JFileChooser selectFileChooser;
  public File fileToRead;
  public File fileToReadTwo;

  /**
   * Creates new form GUI
   */
  public GUI() {
    initComponents();

    selectFileChooser = new JFileChooser();
    selectFileChooser.setCurrentDirectory(new File("c:\\"));
    selectFileChooser.setFileFilter(new FileNameExtensionFilter("CSV, Files", "csv"));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    selectFileButton = new javax.swing.JButton();
    messageLabel = new javax.swing.JLabel();
    instructionLabel1 = new javax.swing.JLabel();
    instructionLabel2 = new javax.swing.JLabel();
    instructionLabel3 = new javax.swing.JLabel();
    instructionLabel4 = new javax.swing.JLabel();
    instructionLabel5 = new javax.swing.JLabel();
    runButton = new javax.swing.JButton();
    selectFileButtonTwo = new javax.swing.JButton();
    messageLabelTwo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("TA Assignment Program");

    selectFileButton.setText("Select File...");
    selectFileButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectFileButtonActionPerformed(evt);
      }
    });

    messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    messageLabel.setText("No file selected.");

    instructionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    instructionLabel1.setText("Hello, and welcome to our TA Assignment Program.");
    instructionLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    instructionLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    instructionLabel2.setText("First, Select your CSV files using the \"Select\" button below.");
    instructionLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    instructionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    instructionLabel3.setText("Afterwards, hit the \"Run\" button to run the program,");
    instructionLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    instructionLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    instructionLabel4
        .setText("and you should receive a CSV file as output, with the TAs organized into");
    instructionLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    instructionLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    instructionLabel5.setText("their appropriate classes.");
    instructionLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    runButton.setText("Run");
    runButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        runButtonActionPerformed(evt);
      }
    });

    selectFileButtonTwo.setText("Select File...");
    selectFileButtonTwo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectFileButtonTwoActionPerformed(evt);
      }
    });

    messageLabelTwo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    messageLabelTwo.setText("No file selected.");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(instructionLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(instructionLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(instructionLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 376,
                        Short.MAX_VALUE)
                    .addComponent(instructionLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(runButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectFileButtonTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageLabelTwo, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabelTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButtonTwo))
                .addGap(12, 12, 12)
                .addComponent(instructionLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runButton)
                .addContainerGap(116, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void selectFileButtonActionPerformed(
      java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
    int returnValue = selectFileChooser.showOpenDialog(this);

    if (returnValue == JFileChooser.APPROVE_OPTION) {
      fileToRead = selectFileChooser.getSelectedFile();
      messageLabel.setText(fileToRead.getName());
    } else {
      messageLabel.setText("No file selected.");
    }
  }//GEN-LAST:event_selectFileButtonActionPerformed

  private void runButtonActionPerformed(
      java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_runButtonActionPerformed

  private void selectFileButtonTwoActionPerformed(
      java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonTwoActionPerformed
    int returnValue = selectFileChooser.showOpenDialog(this);

    if (returnValue == JFileChooser.APPROVE_OPTION) {
      fileToReadTwo = selectFileChooser.getSelectedFile();
      messageLabelTwo.setText(fileToRead.getName());
    } else {
      messageLabelTwo.setText("No file selected.");
    }
  }//GEN-LAST:event_selectFileButtonTwoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel instructionLabel1;
  private javax.swing.JLabel instructionLabel2;
  private javax.swing.JLabel instructionLabel3;
  private javax.swing.JLabel instructionLabel4;
  private javax.swing.JLabel instructionLabel5;
  private javax.swing.JLabel messageLabel;
  private javax.swing.JLabel messageLabelTwo;
  private javax.swing.JButton runButton;
  private javax.swing.JButton selectFileButton;
  private javax.swing.JButton selectFileButtonTwo;
  // End of variables declaration//GEN-END:variables
}
